name: CI

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.x
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
        env:
          CI: true

  test:
    name: Test
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.x
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test
        env:
          CI: true
          # Fix GitHub Actions issue where too many file watchers might potentially lead to issues
          # Original error: "Error from chokidar [...] Error: ENOSPC: System limit for number of file watchers reached [...]"
          # See <https://github.com/cypress-io/cypress/issues/17173#issuecomment-887257762>
          CHOKIDAR_USEPOLLING: 1
